name: ringss_restore_profile
dependencies:
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - ccdproc
      - coveralls
      - sphinx_rtd_theme
      - sphinx
      - tox
      - flake8
